//=============================================================================
// Schach RMMZ - Pathfinding
//=============================================================================

/*:
 *
 * @target MZ
 * @plugindesc Shortest path algorithm implementation.
 * @author Brandt
 * 
 * @help Schach - Pathfinding
 * 
 * This plugin provides implementations of shortest path algorithms that can
 * be used directly with game characters on the map or on generic graph
 * structures.
 * 
 * It is also extensible via definition of custom path finding/following
 * strategies following a common interface.
 *
 */

/*:pt
 *
 * @target MZ
 * @plugindesc Implementação de algoritmo de menor caminho.
 * @author Brandt
 * 
 * @help Schach - Pathfinding
 * 
 * Esse plugin implementa algoritmos de menor caminho que podem ser usados
 * diretamente nos personagens (eventos, jogador, followers, etc) ou em grafos
 * genéricos.
 * 
 * Também é possível extender o plugin definindo estratégias personalizadas de
 * cálculo e seguimento de caminho.
 *
 */

//=============================================================================
// ** NOTICE **
//-----------------------------------------------------------------------------
// The code below is generated by a compiler, and is not well suited for human
// reading. If you are interested on the source code, please take a look at
// the Github repository for this plugin!
//=============================================================================
