name: Tests
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Run tests
        run: |
          npm ci
          npm run coverage
      - name: Upload report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info